version: '3'

services:
    golang:
        build: . # 同一フォルダにあるDockerfileをビルドする
        ports:
            - "8080:8080"
        tty: true # コンテナの起動永続化
        volumes:
            - ./src:/go/src/work
        command: go run main.go # docker-compose run実行時に実行
        container_name: go